import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { AmanahShield } from '@/constants';
import { translations } from '@/translations';
const ChildAppView = ({ childName, lang }) => {
    const t = translations[lang];
    const [isLocked, setIsLocked] = useState(false);
    return (_jsxs("div", { className: "min-h-screen bg-indigo-950 flex flex-col items-center justify-center p-8 text-center text-white", dir: lang === 'ar' ? 'rtl' : 'ltr', children: [_jsx("div", { className: "absolute inset-0 overflow-hidden pointer-events-none", children: _jsx("div", { className: "absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_center,rgba(99,102,241,0.15)_0%,transparent_70%)] animate-pulse" }) }), _jsxs("div", { className: "relative z-10 space-y-12 animate-in fade-in duration-1000", children: [_jsxs("div", { className: "flex flex-col items-center gap-6", children: [_jsx("div", { className: "w-32 h-32 bg-white/10 rounded-[3rem] backdrop-blur-xl border-4 border-indigo-500/50 flex items-center justify-center shadow-[0_0_50px_rgba(99,102,241,0.3)]", children: _jsx(AmanahShield, { className: "w-20 h-20" }) }), _jsxs("div", { className: "space-y-2", children: [_jsx("h2", { className: "text-4xl font-black tracking-tighter", children: t.childModeTitle }), _jsx("p", { className: "text-indigo-300 font-bold text-lg", children: t.childStatusSafe })] })] }), _jsxs("div", { className: "grid grid-cols-1 gap-6 w-full max-w-sm mx-auto", children: [_jsxs("div", { className: "p-8 bg-white/5 border border-white/10 rounded-[2.5rem] backdrop-blur-md", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("span", { className: "text-[10px] font-black uppercase tracking-widest text-indigo-400", children: "\u062D\u0627\u0644\u0629 \u0627\u0644\u0627\u062A\u0635\u0627\u0644" }), _jsx("span", { className: "w-2 h-2 bg-emerald-500 rounded-full animate-pulse" })] }), _jsxs("p", { className: "text-xl font-bold", children: ["\u0645\u0631\u062D\u0628\u0627\u064B ", childName, "\u060C \u062C\u0647\u0627\u0632\u064A \u0645\u0624\u0645\u0646"] })] }), _jsx("div", { className: "grid grid-cols-4 gap-4", children: ['📚', '🎓', '📝', '📞'].map((icon, idx) => (_jsx("div", { className: "w-full aspect-square bg-indigo-900/40 rounded-2xl flex items-center justify-center text-3xl border border-indigo-500/20 shadow-lg", children: icon }, idx))) })] }), _jsx("div", { className: "pt-10", children: _jsxs("div", { className: "flex items-center justify-center gap-3 text-white/40", children: [_jsx("div", { className: "w-2 h-2 bg-white/20 rounded-full" }), _jsx("span", { className: "text-[10px] font-black uppercase tracking-[0.3em]", children: "Amanah Protocol v1.0.4" }), _jsx("div", { className: "w-2 h-2 bg-white/20 rounded-full" })] }) })] })] }));
};
export default ChildAppView;
